export const RESPONSIVE = {
    BREAKPOINT_DESKTOP: {MIN_WIDTH: 992},
    BREAKPOINT_TABLET: { MIN_WIDTH: 768, MAX_WIDTH: 991 },
    BREAKPOINT_MOBILE: { MAX_WIDTH: 767 },
    BREAKPOINT_NOT_MOBILE: { MIN_WIDTH: 768 }  // desktop or tablet or laptop
}
